#obstacle_range: 2.0
#raytrace_range: 2.5
obstacle_range: 2.0
raytrace_range: 2.5
#footprint: [[0.15, 0.25], [0.15, -0.25], [-0.56, -0.25], [-0.56, 0.25]]
#modify by Will cuz arms are too fat
footprint: [[0.15, 0.33], [0.15, -0.33], [-0.4, -0.33], [-0.4, 0.33]]
#footprint: [[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]
#footprint_inflation: 0.01
#robot_radius: 0.175

#inflation_radius: 0.25
#inflation_radius: 0.4   // backup by KKUEI
inflation_radius: 0.6

cost_scaling_factor: 10.0
#inf_is_valid: true
#imax_obstacle_height: 0.6
#min_obstacle_height: 0.0
#observation_sources: scan
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: rplidar, data_type: LaserScan, topic: /rplidar_scan, marking: true, clearing: true, expected_update_rate: 0.4, inf_is_valid: true}
