obstacle_range: 2.0
raytrace_range: 2.5
#footprint: [[0.15, 0.30], [0.15, -0.30], [-0.4, -0.30], [-0.4, 0.30]]
footprint: [[-0.19,0.28],[-0.08,0.28],[0.15,0.24],[0.15,-0.24],[-0.08,-0.28],[-0.19,-0.28],[-0.4,-0.16],[-0.4,0.16]]
#inflation_radius: 0.6
inflation_radius: 0.3

cost_scaling_factor: 10.0
obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: rplidar, data_type: LaserScan, topic: /rplidar_scan, marking: true, clearing: true, expected_update_rate: 0.4, inf_is_valid: true}

sonar_layer:
    topics: ["/sonar1", "/sonar2", "/sonar3", "/sonar6"]
    #topics: ["/sonar1", "/sonar2", "/sonar3", "/sonar4", "/sonar5", "/sonar6", "/sonar7", "/sonar8"]
    no_readings_timeout: 0.0
    clear_threshold: 0.001
    mark_threshold: 0.996
    clear_on_max_reading: true
